/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/nAvIt2gAjZh
 */
import Link from "next/link"
import { JSX, SVGProps } from "react"
import AddExpense from "./addExpense"

export function Navbar() {
  return (
    <footer className="fixed inset-x-0 bottom-0 flex items-center justify-center h-16 px-4 bg-gray-50 dark:bg-gray-950 sm:px-6 max-w-lg">
      <Link
        className="flex-1 flex flex-col items-center justify-center text-sm opacity-50 hover:opacity-100 transition-opacity"
        href="#"
      >
        <HomeIcon className="h-6 w-6" />
        Home
      </Link>
      <Link
        className="flex-1 flex flex-col items-center justify-center text-sm opacity-50 hover:opacity-100 transition-opacity"
        href="#"
      >
        <UserIcon className="h-6 w-6" />
        Profile
      </Link>
      <AddExpense
      ></AddExpense>
    </footer>
  )
}


function HomeIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  )
}


function UserIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}



